### PR TITLE
Feat/homepage

### PR DESCRIPTION
**Pull request by ha-anna**
1. Coded homepage. 

Components:
- Nav
- Hero
- Map with MapBox
- Footer

2. Set up tailwind custom variables for future use:

```
  theme: {
    extend: {
      colors: {
        artemis: {
          white: '#FFFDFA',
          black: '#212427',
          gray: 'rgba(33, 36, 39, 0.66)',
          blue: '#00BFFF',
          green: '#8BC34A',
          yellow: '#FFD700'
          }
      },
      backgroundColor: {
        white: '#FFFDFA',
      },
      borderColor: {
        artemis: {
          blue: '#00BFFF',
          gray: 'rgba(33, 36, 39, 0.66)',
          black: '#212427',
          green: '#8BC34A',
          yellow: '#FFD700'
        }
      },
      backgroundImage: {
        'hero-gradient': "url('/images/hero-gradient.svg')",
      }
    },
  },
  ```

3. Added Radix (haven't used it yet)
4. Whoever deploys it the environment variable is necessary - MapBox API Key, I've posted it in the discord @nubiv 
5. Also updated README - Horus changed his github name and now we have a deployed FE so I can link it there

### CODE REVIEW

**Comment by ha-anna** [comment]
Screenshot of the design:
FireShot Capture 010 - Artemis - Helping strays, one location at a time  - localhost

**Review by nubiv — APPROVED** [review]

**Comment by nubiv** [comment]
Just added a bit refactoring but not sure why that did not go through in this PR.
I noticed that the page currently doesn't fit well on smaller screens but we can fix it later on. Nevertheless awesome work @ha-anna 😄!

**Comment by nubiv** [comment]
Btw I think we can remove Radixui from dependencies since it doesn't seem to be necessary for you haha 🤣

**Comment by ha-anna** [comment]
Great, then I will make it responsive today and add a mobile navbar since I didn't yet. 

@nubiv  I think we can incorporate RadixUI for the logged-in user dropdown menu so I will leave it for now. 😃

**Comment by nubiv** [comment]
Btw I just figured it out. Since your pr comes from your forked repo I cant commit anything into it 😅. The refactoring change I made was pushed into the branch in the main repo. Feel free to check it our or merge it when you get a chance. @ha-anna

**Comment by ha-anna** [comment]
I merged after some improvements and now I will merge @nubiv 's improvements too.
Will open a new branch to work on Nav more since it's probably will take a while.

**Pull request merged**
